[versions]
agp = "8.11.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
composeBom = "2024.09.00"
tvFoundation = "1.0.0-alpha07"
tvMaterial = "1.0.0-alpha07"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.10.1"
credentials = "1.6.0-alpha05"
identify = "1.0.0"
coroutines = "1.10.2"
koin = "4.1.1"
ktor-client = "2.1.1"
timber = "5.0.1"
navigation = "2.9.6"
datastoreCore = "1.2.0"
jetbrains-kotlinx-serialization = "1.8.1" #required kotlin 2.2.0 to update to newest version (1.9.0)
play-services-auth = "20.5.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tvFoundation" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tvMaterial" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
androidx-data-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreCore" }

androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }
identify = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "identify" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

jetbrains-kotlinx-serialization = {group="org.jetbrains.kotlinx", name="kotlinx-serialization-json", version.ref="jetbrains-kotlinx-serialization"}

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor-client" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor-client" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor-client" }
ktor-client-gson = { group = "io.ktor", name = "ktor-client-gson", version.ref = "ktor-client" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor-client" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor-client" }
ktor-client-contentnegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor-client" }
ktor-client-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-client" }

play-services-auth = {group="com.google.android.gms", name="play-services-auth", version.ref="play-services-auth"}

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
credentials = ["androidx-credentials", "androidx-credentials-play-services-auth", "identify"]
koin = ["koin", "koin-android", "koin-androidx-compose"]
ktor = ["ktor-client", "ktor-client-android", "ktor-client-okhttp", "ktor-client-gson", "ktor-client-logging", "ktor-client-auth", "ktor-client-contentnegotiation", "ktor-client-json"]

datastore = ["androidx-datastore-core", "androidx-data-preferences"]



